#FROM postgres:latest AS postgres
#
#ENV POSTGRES_USER=root
#ENV POSTGRES_PASSWORD=root
#ENV POSTGRES_DB=mspr_kawa_bdd_main
#
#EXPOSE 5432

FROM openjdk:17

WORKDIR /app

COPY target/mspr_kawa_bdd_main.jar /app/mspr_kawa_bdd_main.jar

EXPOSE 8077:8077

CMD ["java", "-jar", "mspr_kawa_bdd_main.jar"]
