version: '3'

services:

  nginx:
    build: .
    image: mspr-kawa-nginx
    container_name: mspr-kawa-nginx
    ports:
      - "8082:8082"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./html/50x.html:/usr/share/nginx/html/50x.html

  mspr-kawa-keycloak:
    build: ./keycloak/.
    image: mspr-kawa-keycloak
    container_name: mspr-kawa-keycloak
    ports:
      - "8081:8081"

  mspr-kawa-postgresql:
    build: ./postgresql/.
    image: postgresql
    container_name: postgresql
    ports:
      - "5432:5432"
    restart: always

  mspr-kawa-rabbitmq:
    build: ./rabbitMQ/.
    image: mspr-kawwa-rabbitmq
    container_name: mspr-kawwa-rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
#
#  mspr-kawa-clients:
#    image: mspr-kawa-clients
#    container_name: mspr-kawa-clients
#    environment:
#      - SPRING_PROFILES_ACTIVE=prod
#    ports:
#      - "8080:8080"
#    networks:
#      - mspr-kawa-network
#    depends_on:
#      mspr-kawa-db:
#        condition: service_started
#
##  mspr-kawa-orders:
##    image: mspr-kawa-orders
##    container_name: mspr-kawa-orders
##    ports:
##      - "8079:8079"
##    networks:
##      - mspr-kawa-network
#
##  mspr-kawa-products:
##    image: mspr-kawa-products
##    container_name: mspr-kawa-products
##    ports:
##      - "8078:8078
##    networks:
##      - mspr-kawa-network
#
#  mspr-kawa-db:
#    image: mspr-kawa-db
#    container_name: mspr-kawa-db
#    environment:
#      - SPRING_PROFILES_ACTIVE=prod
#    ports:
#      - "8077:8077"
#    networks:
#      - mspr-kawa-network
#    depends_on:
#      - mspr-kawa-postgresql
