version: '3'

networks:
  mspr-kawa-network:
    driver: bridge

services:

#  nginx:
#    image: mspr-kawa-nginx
#    container_name: mspr-kawa-nginx
#    ports:
#      - "8082:8082"
#    networks:
#      - mspr-kawa-network
#    volumes:
#      - ./conf/nginx.conf:/etc/nginx/nginx.conf
#      - ./html/50x.html:/usr/share/nginx/html/50x.html
#    depends_on:
#      - clients
#      - keycloak

  mspr-kawa-keycloak:
    image: mspr-kawa-keycloak
    container_name: mspr-kawa-keycloak
    ports:
      - "8081:8081"
    networks:
      - mspr-kawa-network

  mspr-kawa-clients:
    image: mspr-kawa-clients
    container_name: mspr-kawa-clients
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    networks:
      - mspr-kawa-network
    depends_on:
      mspr-kawa-db:
        condition: service_started

#  mspr-kawa-orders:
#    image: mspr-kawa-orders
#    container_name: mspr-kawa-orders
#    ports:
#      - "8079:8079"
#    networks:
#      - mspr-kawa-network

#  mspr-kawa-products:
#    image: mspr-kawa-products
#    container_name: mspr-kawa-products
#    ports:
#      - "8078:8078
#    networks:
#      - mspr-kawa-network

  mspr-kawa-db:
    image: mspr-kawa-db
    container_name: mspr-kawa-db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8077:8077"
    networks:
      - mspr-kawa-network
    depends_on:
      - mspr-kawa-postgresql

  mspr-kawa-postgresql:
    image: postgresql
    container_name: postgresql
    ports:
      - "5432:5432"
    networks:
      - mspr-kawa-network
